"""initial schema

Revision ID: 39bcbd65b69a
Revises: 
Create Date: 2026-07-12 20:39:05.519877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '39bcbd65b69a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_cutoff', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'start_year')
    )
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'alias')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('ft_home', sa.Integer(), nullable=False),
    sa.Column('ft_away', sa.Integer(), nullable=False),
    sa.Column('ht_home', sa.Integer(), nullable=True),
    sa.Column('ht_away', sa.Integer(), nullable=True),
    sa.Column('shots_home', sa.Integer(), nullable=True),
    sa.Column('shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_away', sa.Integer(), nullable=True),
    sa.Column('corners_home', sa.Integer(), nullable=True),
    sa.Column('corners_away', sa.Integer(), nullable=True),
    sa.Column('yellows_home', sa.Integer(), nullable=True),
    sa.Column('yellows_away', sa.Integer(), nullable=True),
    sa.Column('reds_home', sa.Integer(), nullable=True),
    sa.Column('reds_away', sa.Integer(), nullable=True),
    sa.Column('fouls_home', sa.Integer(), nullable=True),
    sa.Column('fouls_away', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'match_date', 'home_team_id', 'away_team_id')
    )
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'])
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'])
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'])
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker', 'market', 'selection', 'line', 'is_closing')
    )
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'])
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'match_id', 'market', 'selection', 'line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('team_aliases')
    op.drop_table('seasons')
    op.drop_table('teams')
    op.drop_table('model_runs')
    op.drop_table('leagues')
    op.drop_table('backtests')
    # ### end Alembic commands ###
