"""injuries table

Revision ID: 96560fcb3148
Revises: 7c1a2e9d4b02
Create Date: 2026-07-14 21:52:23.192584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96560fcb3148'
down_revision: Union[str, None] = '7c1a2e9d4b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'match_date', 'player_name')
    )
    op.create_index(op.f('ix_injuries_match_date'), 'injuries', ['match_date'], unique=False)
    op.create_index(op.f('ix_injuries_team_id'), 'injuries', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_injuries_team_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_match_date'), table_name='injuries')
    op.drop_table('injuries')
    # ### end Alembic commands ###
